# Generated by Django 4.0.3 on 2022-04-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='details',
            name='task_completed',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
